In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df=sns.load_dataset("titanic")
df

     survived  pclass     sex   age  sibsp  parch     fare  ...   class    who adult_male  deck  embark_town alive  alone
0           0       3    male  22.0      1      0   7.2500  ...   Third    man       True   NaN  Southampton    no  False
1           1       1  female  38.0      1      0  71.2833  ...   First  woman      False     C    Cherbourg   yes  False
2           1       3  female  26.0      0      0   7.9250  ...   Third  woman      False   NaN  Southampton   yes   True
3           1       1  female  35.0      1      0  53.1000  ...   First  woman      False     C  Southampton   yes  False
4           0       3    male  35.0      0      0   8.0500  ...   Third    man       True   NaN  Southampton    no   True
..        ...     ...     ...   ...    ...    ...      ...  ...     ...    ...        ...   ...          ...   ...    ...
886         0       2    male  27.0      0      0  13.0000  ...  Second    man       True   NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.0000  ...   First  woman      False     B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.4500  ...   Third  woman      False   NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.0000  ...   First    man       True     C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.7500  ...   Third    man       True   NaN   Queenstown    no   True

[891 rows x 15 columns]

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [5]:
df.head(5)

   survived  pclass     sex   age  sibsp  parch     fare  ...  class    who adult_male  deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500  ...  Third    man       True   NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833  ...  First  woman      False     C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250  ...  Third  woman      False   NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000  ...  First  woman      False     C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500  ...  Third    man       True   NaN  Southampton    no   True

[5 rows x 15 columns]

In [6]:
df.tail(5)

     survived  pclass     sex   age  sibsp  parch   fare  ...   class    who adult_male  deck  embark_town alive  alone
886         0       2    male  27.0      0      0  13.00  ...  Second    man       True   NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.00  ...   First  woman      False     B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.45  ...   Third  woman      False   NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.00  ...   First    man       True     C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.75  ...   Third    man       True   NaN   Queenstown    no   True

[5 rows x 15 columns]

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [8]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [10]:
df=df.drop(columns=['age','deck'])

In [11]:
df.head(5)

   survived  pclass     sex  sibsp  parch     fare embarked  class    who  adult_male  embark_town alive  alone
0         0       3    male      1      0   7.2500        S  Third    man        True  Southampton    no  False
1         1       1  female      1      0  71.2833        C  First  woman       False    Cherbourg   yes  False
2         1       3  female      0      0   7.9250        S  Third  woman       False  Southampton   yes   True
3         1       1  female      1      0  53.1000        S  First  woman       False  Southampton   yes  False
4         0       3    male      0      0   8.0500        S  Third    man        True  Southampton    no   True

In [12]:
df.columns

Index(['survived', 'pclass', 'sex', 'sibsp', 'parch', 'fare', 'embarked',
       'class', 'who', 'adult_male', 'embark_town', 'alive', 'alone'],
      dtype='str')

In [13]:
df.isnull().sum()

survived       0
pclass         0
sex            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [14]:
df['embarked']=df['embarked'].fillna('C',inplace=True)
df.head(10)

   survived  pclass     sex  sibsp  parch     fare embarked   class    who  adult_male  embark_town alive  alone
0         0       3    male      1      0   7.2500        S   Third    man        True  Southampton    no  False
1         1       1  female      1      0  71.2833        C   First  woman       False    Cherbourg   yes  False
2         1       3  female      0      0   7.9250        S   Third  woman       False  Southampton   yes   True
3         1       1  female      1      0  53.1000        S   First  woman       False  Southampton   yes  False
4         0       3    male      0      0   8.0500        S   Third    man        True  Southampton    no   True
5         0       3    male      0      0   8.4583        Q   Third    man        True   Queenstown    no   True
6         0       1    male      0      0  51.8625        S   First    man        True  Southampton    no   True
7         0       3    male      3      1  21.0750        S   Third  child       False  Southampton    no  False
8         1       3  female      0      2  11.1333        S   Third  woman       False  Southampton   yes  False
9         1       2  female      1      0  30.0708        C  Second  child       False    Cherbourg   yes  False

In [15]:
df['embark_town']=df['embark_town'].fillna('Cherbourg',inplace=True)
df.head(10)

   survived  pclass     sex  sibsp  parch     fare embarked   class    who  adult_male  embark_town alive  alone
0         0       3    male      1      0   7.2500        S   Third    man        True  Southampton    no  False
1         1       1  female      1      0  71.2833        C   First  woman       False    Cherbourg   yes  False
2         1       3  female      0      0   7.9250        S   Third  woman       False  Southampton   yes   True
3         1       1  female      1      0  53.1000        S   First  woman       False  Southampton   yes  False
4         0       3    male      0      0   8.0500        S   Third    man        True  Southampton    no   True
5         0       3    male      0      0   8.4583        Q   Third    man        True   Queenstown    no   True
6         0       1    male      0      0  51.8625        S   First    man        True  Southampton    no   True
7         0       3    male      3      1  21.0750        S   Third  child       False  Southampton    no  False
8         1       3  female      0      2  11.1333        S   Third  woman       False  Southampton   yes  False
9         1       2  female      1      0  30.0708        C  Second  child       False    Cherbourg   yes  False

In [16]:
df.isnull().sum()

survived       0
pclass         0
sex            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [17]:
df=df.drop(columns=['class','who','adult_male','embark_town','alive','alone'])
df.head(5)

   survived  pclass     sex  sibsp  parch     fare embarked
0         0       3    male      1      0   7.2500        S
1         1       1  female      1      0  71.2833        C
2         1       3  female      0      0   7.9250        S
3         1       1  female      1      0  53.1000        S
4         0       3    male      0      0   8.0500        S

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex'] =le.fit_transform(df['sex'])

In [19]:
df.head(5)

   survived  pclass  sex  sibsp  parch     fare embarked
0         0       3    1      1      0   7.2500        S
1         1       1    0      1      0  71.2833        C
2         1       3    0      0      0   7.9250        S
3         1       1    0      1      0  53.1000        S
4         0       3    1      0      0   8.0500        S

In [20]:
df['embarked'].unique()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [21]:
df=pd.get_dummies(df,columns=['embarked'],dtype=int)

In [25]:
df.head(5)

   survived  pclass  sex  sibsp  parch     fare  embarked_C  embarked_Q  embarked_S
0         0       3    1      1      0   7.2500           0           0           1
1         1       1    0      1      0  71.2833           1           0           0
2         1       3    0      0      0   7.9250           0           0           1
3         1       1    0      1      0  53.1000           0           0           1
4         0       3    1      0      0   8.0500           0           0           1

In [27]:
X = df.drop('survived', axis=1)
y = df['survived']

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

model.fit(X_train,y_train)

GaussianNB()

In [30]:
y_pred=model.predict(X_test)

In [31]:
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [32]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [34]:
accuracy_score(y_test,y_pred)

0.776536312849162

In [35]:
confusion_matrix(y_test,y_pred)

array([[82, 23],
       [17, 57]])

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.78      0.80       105
           1       0.71      0.77      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179

In [37]:
X

     pclass  sex  sibsp  parch     fare  embarked_C  embarked_Q  embarked_S
0         3    1      1      0   7.2500           0           0           1
1         1    0      1      0  71.2833           1           0           0
2         3    0      0      0   7.9250           0           0           1
3         1    0      1      0  53.1000           0           0           1
4         3    1      0      0   8.0500           0           0           1
..      ...  ...    ...    ...      ...         ...         ...         ...
886       2    1      0      0  13.0000           0           0           1
887       1    0      0      0  30.0000           0           0           1
888       3    0      1      2  23.4500           0           0           1
889       1    1      0      0  30.0000           1           0           0
890       3    1      0      0   7.7500           0           1           0

[891 rows x 8 columns]

In [47]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [43]:
new_data=[[12,0,0,1,8.1100,0,0,1]]

In [44]:
pre=model.predict(new_data)
print("Prediction:",pre)

Prediction: [1]

In [45]:
if pre[0] == 1:
    print("Person is survived!!!!!!!!")
else:
    print("Person is not survived!!!!!!!!!!!!")

Person is survived!!!!!!!!